"use client";
import { FormEvent, useEffect, useState } from "react";
import { BookOpen, Plus, Database } from "lucide-react";
import { aiApi } from "@/services/ai.service";
export default function KnowledgePage(){
 const [items,setItems]=useState<any[]>([]),[title,setTitle]=useState(""),[content,setContent]=useState(""),[error,setError]=useState("");
 const load=async()=>{try{setItems(await aiApi.knowledge())}catch(e:any){setError(e?.response?.data?.detail||"Unable to load knowledge base.")}};useEffect(()=>{void load()},[]);
 async function submit(e:FormEvent){e.preventDefault();setError("");try{await aiApi.addKnowledge({Title:title,Content:content,SourceType:"text"});setTitle("");setContent("");await load()}catch(err:any){setError(err?.response?.data?.detail||"Unable to index document.")}}
 return <div className="space-y-6 text-slate-900"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-700">RAG Knowledge</p><h1 className="mt-1 text-3xl font-black text-slate-950">Knowledge Base</h1><p className="mt-2 text-slate-600">Add trusted material used by the Intellix AI assistant.</p></div>{error&&<div className="rounded-xl border border-red-300 bg-red-50 p-4 font-semibold text-red-800">{error}</div>}<form onSubmit={submit} className="space-y-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div><label className="mb-2 block text-sm font-bold text-slate-800">Document title</label><input required value={title} onChange={e=>setTitle(e.target.value)} className="h-12 w-full rounded-xl border border-slate-300 bg-white px-4 text-slate-950 outline-none placeholder:text-slate-400 focus:border-blue-600 focus:ring-4 focus:ring-blue-100" placeholder="e.g. Employee handbook"/></div><div><label className="mb-2 block text-sm font-bold text-slate-800">Content</label><textarea required minLength={20} value={content} onChange={e=>setContent(e.target.value)} className="min-h-48 w-full rounded-xl border border-slate-300 bg-white p-4 text-slate-950 outline-none placeholder:text-slate-400 focus:border-blue-600 focus:ring-4 focus:ring-blue-100" placeholder="Paste company policy, course material, service information or project documentation"/></div><button className="inline-flex items-center gap-2 rounded-xl bg-blue-700 px-5 py-3 font-bold text-white hover:bg-blue-800"><Plus size={18}/>Add and index</button></form><div><div className="mb-3 flex items-center gap-2"><Database className="text-blue-700"/><h2 className="text-xl font-black text-slate-950">Indexed documents</h2></div><div className="grid gap-4 md:grid-cols-2">{items.length===0?<div className="rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center text-slate-600">No documents indexed yet.</div>:items.map(x=><div key={x.KnowledgeDocumentID} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><BookOpen className="mb-3 text-blue-700"/><div className="font-bold text-slate-950">{x.Title}</div><div className="mt-1 text-sm text-slate-600">{x.SourceType||"text"}</div></div>)}</div></div></div>
}
