"use client";
import {useEffect,useMemo,useState}from"react";
import Link from"next/link";
import{BookOpen,CheckCircle2,TrendingUp,FileText,Award,ArrowRight,GraduationCap}from"lucide-react";
import LmsShell from"@/components/lms/LmsShell";
import{Card,Empty,PageTitle}from"@/components/lms/Ui";
import{lmsApi}from"@/lib/lms";
import api from"@/lib/api";
import type{MyCourse}from"@/types/lms";

export default function StudentDashboardPage(){
 const[courses,setCourses]=useState<MyCourse[]>([]);const[name,setName]=useState("Student");const[loading,setLoading]=useState(true);
 useEffect(()=>{Promise.all([lmsApi.myCourses(),api.get("/portal/me")]).then(([c,u])=>{setCourses(c);setName(u.data?.FullName||"Student")}).finally(()=>setLoading(false))},[]);
 const stats=useMemo(()=>({enrolled:courses.length,completed:courses.filter(x=>x.progress>=100||x.status==="completed").length,average:courses.length?Math.round(courses.reduce((n,x)=>n+x.progress,0)/courses.length):0}),[courses]);
 return <LmsShell mode="student"><div className="mb-6 rounded-3xl bg-gradient-to-r from-blue-700 to-indigo-800 p-7 text-white shadow-lg"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><div className="mb-3 flex h-11 w-11 items-center justify-center rounded-xl bg-white/15"><GraduationCap/></div><h1 className="text-3xl font-black">Welcome back, {name}</h1><p className="mt-2 max-w-2xl text-blue-100">Continue lessons, submit assignments and track your academy progress.</p></div><Link href="/portal/student/courses" className="inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 font-bold text-blue-700">Continue learning <ArrowRight size={18}/></Link></div></div><PageTitle title="Learning overview" description="Everything assigned to your student account"/><div className="grid gap-4 md:grid-cols-3"><Stat title="Enrolled courses" value={stats.enrolled} icon={<BookOpen/>}/><Stat title="Completed" value={stats.completed} icon={<CheckCircle2/>}/><Stat title="Average progress" value={`${stats.average}%`} icon={<TrendingUp/>}/></div><div className="mt-8 grid gap-4 md:grid-cols-2"><Link href="/portal/student/assignments"><Card className="h-full transition hover:border-blue-300"><FileText className="text-blue-700"/><h2 className="mt-3 font-bold text-slate-950">Assignments</h2><p className="mt-1 text-sm text-slate-600">Open coursework and submit answers or resource links.</p></Card></Link><Link href="/portal/student/results"><Card className="h-full transition hover:border-blue-300"><Award className="text-blue-700"/><h2 className="mt-3 font-bold text-slate-950">Results & feedback</h2><p className="mt-1 text-sm text-slate-600">Review marks and instructor feedback after grading.</p></Card></Link></div><section className="mt-8"><h2 className="mb-4 text-xl font-black text-slate-950">My courses</h2>{loading?<Card>Loading your courses...</Card>:courses.length?<div className="grid gap-4 lg:grid-cols-2">{courses.slice(0,4).map(x=><Card key={x.enrollment_id}><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold text-slate-950">{x.course.Title}</h3><p className="mt-1 text-sm text-slate-600">{x.course.ShortDescription||"Intellix Academy course"}</p></div><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">{x.status}</span></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-blue-600" style={{width:`${x.progress}%`}}/></div><div className="mt-3 flex items-center justify-between text-sm"><span className="font-semibold text-slate-700">{Math.round(x.progress)}% complete</span><Link href={`/portal/student/courses/${x.course.CourseID}`} className="font-bold text-blue-700">Open course →</Link></div></Card>)}</div>:<Empty text="No courses are assigned yet. An administrator or instructor can enroll you from the LMS."/>}</section></LmsShell>
}
function Stat({title,value,icon}:{title:string;value:string|number;icon:React.ReactNode}){return <Card><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-slate-600">{title}</p><p className="mt-2 text-3xl font-black text-slate-950">{value}</p></div><div className="rounded-xl bg-blue-50 p-3 text-blue-700">{icon}</div></div></Card>}
