"use client";
import { FormEvent, useState } from "react";
import { Bot, Send, Sparkles, BookOpen, AlertCircle } from "lucide-react";
import { aiApi, AISource } from "@/services/ai.service";
export default function AIPage(){
 const [message,setMessage]=useState(""),[answer,setAnswer]=useState(""),[sources,setSources]=useState<AISource[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState("");const [conversation,setConversation]=useState<number>();
 async function submit(e:FormEvent){e.preventDefault();if(!message.trim())return;setLoading(true);setError("");try{const r=await aiApi.chat(message.trim(),conversation);setAnswer(r.answer||"No answer returned.");setSources(r.sources||[]);setConversation(r.conversation_id)}catch(err:any){setError(err?.response?.data?.detail||"AI request failed. Check your backend and LLM configuration.")}finally{setLoading(false)}}
 return <div className="mx-auto max-w-6xl space-y-6 text-slate-900">
  <section className="overflow-hidden rounded-3xl bg-gradient-to-r from-slate-950 via-blue-950 to-indigo-950 p-8 text-white shadow-xl"><div className="flex items-start gap-4"><div className="rounded-2xl bg-blue-600 p-3"><Bot size={28}/></div><div><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-300">AI Workspace</p><h1 className="mt-2 text-3xl font-black">Intellix AI Assistant</h1><p className="mt-2 max-w-2xl text-slate-300">Ask questions across your authorized company knowledge, CRM context, academy material and project documentation.</p></div></div></section>
  {error&&<div className="flex gap-3 rounded-2xl border border-red-300 bg-red-50 p-4 font-semibold text-red-800"><AlertCircle size={20}/>{error}</div>}
  <form onSubmit={submit} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><label className="mb-2 block text-sm font-bold text-slate-800">Ask Intellix AI</label><textarea required value={message} onChange={e=>setMessage(e.target.value)} className="min-h-32 w-full resize-y rounded-xl border border-slate-300 bg-white p-4 text-slate-950 outline-none placeholder:text-slate-400 focus:border-blue-600 focus:ring-4 focus:ring-blue-100" placeholder="Ask about customers, policies, courses, projects or company knowledge..."/><div className="mt-3 flex justify-end"><button disabled={loading} className="inline-flex items-center gap-2 rounded-xl bg-blue-700 px-6 py-3 font-bold text-white hover:bg-blue-800 disabled:bg-slate-400">{loading?<Sparkles className="animate-pulse" size={18}/>:<Send size={18}/>} {loading?"Thinking...":"Ask AI"}</button></div></form>
  {answer&&<section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-4 flex items-center gap-2 font-black text-slate-950"><Sparkles className="text-blue-700" size={20}/>Answer</div><div className="whitespace-pre-wrap leading-7 text-slate-800">{answer}</div></section>}
  {sources.length>0&&<section><div className="mb-3 flex items-center gap-2"><BookOpen className="text-blue-700" size={20}/><h2 className="text-lg font-black text-slate-950">Sources</h2></div><div className="grid gap-3">{sources.map(s=><div key={s.chunk_id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="font-bold text-slate-950">{s.title}</div><div className="mt-1 text-sm leading-6 text-slate-600">{s.excerpt}</div></div>)}</div></section>}
 </div>
}
