"use client";
import { useEffect, useState } from "react";
import { Plus, Shield, Pencil, Trash2, X } from "lucide-react";
import api from "@/lib/api";

type Role={RoleID:number;RoleName:string;Description?:string|null};
export default function RolesPage(){
 const [roles,setRoles]=useState<Role[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const [open,setOpen]=useState(false),[editing,setEditing]=useState<Role|null>(null),[name,setName]=useState(""),[desc,setDesc]=useState("");
 const load=async()=>{try{setLoading(true);setError("");const r=await api.get("/roles/");setRoles(Array.isArray(r.data)?r.data:[])}catch(e:any){setError(e?.response?.data?.detail||"Unable to load roles.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const start=(r?:Role)=>{setEditing(r||null);setName(r?.RoleName||"");setDesc(r?.Description||"");setOpen(true)};
 const save=async()=>{if(!name.trim())return setError("Role name is required.");try{const payload={RoleName:name.trim(),Description:desc.trim()};editing?await api.put(`/roles/${editing.RoleID}`,payload):await api.post("/roles/",payload);setOpen(false);await load()}catch(e:any){setError(e?.response?.data?.detail||"Unable to save role.")}};
 const remove=async(r:Role)=>{if(!confirm(`Delete role ${r.RoleName}?`))return;try{await api.delete(`/roles/${r.RoleID}`);await load()}catch(e:any){setError(e?.response?.data?.detail||"Unable to delete role.")}};
 return <div className="space-y-6 text-slate-900">
  <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold uppercase tracking-widest text-blue-700">Access Control</p><h1 className="mt-1 text-3xl font-black text-slate-950">Roles Management</h1><p className="mt-2 text-slate-600">Create and manage platform access roles.</p></div><button onClick={()=>start()} className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-700 px-5 py-3 font-bold text-white hover:bg-blue-800"><Plus size={18}/>Add Role</button></div>
  {error&&<div className="rounded-xl border border-red-300 bg-red-50 px-4 py-3 font-semibold text-red-800">{error}</div>}
  <div className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl bg-slate-950 p-5 text-white"><Shield className="mb-4 text-cyan-400"/><p className="text-sm text-slate-400">Total Roles</p><p className="text-3xl font-black">{roles.length}</p></div></div>
  <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{loading?<div className="p-10 text-center text-slate-600">Loading roles...</div>:<div className="overflow-x-auto"><table className="w-full"><thead className="bg-slate-100 text-left text-sm text-slate-700"><tr><th className="px-6 py-4">ID</th><th className="px-6 py-4">Role</th><th className="px-6 py-4">Description</th><th className="px-6 py-4 text-right">Actions</th></tr></thead><tbody>{roles.map(r=><tr key={r.RoleID} className="border-t border-slate-200"><td className="px-6 py-4 text-slate-600">{r.RoleID}</td><td className="px-6 py-4"><span className="rounded-full bg-blue-100 px-3 py-1 text-sm font-bold text-blue-800">{r.RoleName}</span></td><td className="px-6 py-4 text-slate-700">{r.Description||"—"}</td><td className="px-6 py-4"><div className="flex justify-end gap-2"><button onClick={()=>start(r)} className="rounded-lg bg-slate-100 p-2 text-slate-700 hover:bg-slate-200"><Pencil size={16}/></button><button onClick={()=>void remove(r)} className="rounded-lg bg-red-50 p-2 text-red-700 hover:bg-red-100"><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div>}</div>
  {open&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-black text-slate-950">{editing?"Edit Role":"Create Role"}</h2><button onClick={()=>setOpen(false)} className="rounded-lg p-2 text-slate-600 hover:bg-slate-100"><X size={20}/></button></div><div className="space-y-4"><div><label className="mb-2 block text-sm font-bold text-slate-800">Role name</label><input value={name} onChange={e=>setName(e.target.value)} className="h-12 w-full rounded-xl border border-slate-300 bg-white px-4 text-slate-950 outline-none focus:border-blue-600 focus:ring-4 focus:ring-blue-100"/></div><div><label className="mb-2 block text-sm font-bold text-slate-800">Description</label><textarea value={desc} onChange={e=>setDesc(e.target.value)} className="min-h-28 w-full rounded-xl border border-slate-300 bg-white p-4 text-slate-950 outline-none focus:border-blue-600 focus:ring-4 focus:ring-blue-100"/></div><button onClick={()=>void save()} className="h-12 w-full rounded-xl bg-blue-700 font-bold text-white hover:bg-blue-800">{editing?"Update Role":"Create Role"}</button></div></div></div>}
 </div>
}
