"use client";
import{useEffect,useMemo,useState}from"react";
import api from"@/lib/api";
import LmsShell from"@/components/lms/LmsShell";
import{Card,Empty,ErrorBox,PageTitle,btn,input}from"@/components/lms/Ui";
import{lmsApi}from"@/lib/lms";
import type{Course,Enrollment}from"@/types/lms";
type User={UserID:number;FullName:string;Email:string;RoleID:number};type Role={RoleID:number;RoleName:string};
export default function Page(){const[items,setItems]=useState<Enrollment[]>([]);const[courses,setCourses]=useState<Course[]>([]);const[users,setUsers]=useState<User[]>([]);const[roles,setRoles]=useState<Role[]>([]);const[student,setStudent]=useState(0);const[course,setCourse]=useState(0);const[error,setError]=useState("");const load=()=>Promise.all([lmsApi.enrollments(),lmsApi.courses(),api.get<User[]>("/users/"),api.get<Role[]>("/roles/")]).then(([e,c,u,r])=>{setItems(e);setCourses(c);setUsers(u.data);setRoles(r.data);if(!course&&c[0])setCourse(c[0].CourseID)});useEffect(()=>{void load().catch(()=>setError("Unable to load enrollments"))},[]);const studentRole=roles.find(r=>r.RoleName?.toUpperCase()==="STUDENT")?.RoleID;const students=useMemo(()=>users.filter(u=>studentRole?u.RoleID===studentRole:false),[users,studentRole]);async function submit(e:React.FormEvent){e.preventDefault();setError("");if(!student||!course){setError("Choose a student and course");return}try{await lmsApi.enroll(student,course);setStudent(0);await load()}catch(e:any){setError(e.response?.data?.detail||"Unable to enroll student")}}return <LmsShell mode="admin"><PageTitle title="Enrollments" description="Assign registered STUDENT accounts to published academy courses."/>{error&&<ErrorBox text={error}/>}<Card className="mb-6"><form onSubmit={submit} className="grid gap-3 md:grid-cols-[1fr_1fr_auto]"><select className={input} value={student} onChange={e=>setStudent(Number(e.target.value))} required><option value={0}>Choose student</option>{students.map(u=><option key={u.UserID} value={u.UserID}>{u.FullName} · {u.Email}</option>)}</select><select className={input} value={course} onChange={e=>setCourse(Number(e.target.value))}>{courses.map(c=><option value={c.CourseID} key={c.CourseID}>{c.Title}</option>)}</select><button className={btn}>Enroll student</button></form>{!students.length&&<p className="mt-3 text-sm text-amber-700">No STUDENT users found. Ask the learner to register from Student Registration first.</p>}</Card><div className="overflow-x-auto rounded-xl border border-slate-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-700"><tr><th className="p-3">Student</th><th className="p-3">Course</th><th className="p-3">Status</th><th className="p-3">Progress</th></tr></thead><tbody>{items.map(x=><tr className="border-t" key={x.EnrollmentID}><td className="p-3 font-semibold text-slate-900">{x.student?.FullName||`User #${x.StudentID}`}<br/><span className="text-xs font-normal text-slate-500">{x.student?.Email}</span></td><td className="p-3">{x.course?.Title||`Course #${x.CourseID}`}</td><td className="p-3 capitalize">{x.Status}</td><td className="p-3"><span className="font-bold text-blue-700">{Number(x.ProgressPercent||0)}%</span></td></tr>)}</tbody></table></div>{!items.length&&<Empty text="No enrollments yet."/>}</LmsShell>}
