USE intellixDB;
GO

IF OBJECT_ID('Organizations','U') IS NULL
CREATE TABLE Organizations(
 OrganizationID INT IDENTITY PRIMARY KEY, Name NVARCHAR(180) NOT NULL,
 Slug NVARCHAR(180) NOT NULL UNIQUE, Industry NVARCHAR(120), Website NVARCHAR(255),
 IsActive BIT NOT NULL DEFAULT 1, CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);
GO
IF OBJECT_ID('Departments','U') IS NULL
CREATE TABLE Departments(
 DepartmentID INT IDENTITY PRIMARY KEY, OrganizationID INT NULL REFERENCES Organizations(OrganizationID),
 Name NVARCHAR(140) NOT NULL, Description NVARCHAR(500), ManagerUserID INT NULL REFERENCES Users(UserID),
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);
GO
IF OBJECT_ID('Employees','U') IS NULL
CREATE TABLE Employees(
 EmployeeID INT IDENTITY PRIMARY KEY, OrganizationID INT NULL REFERENCES Organizations(OrganizationID),
 UserID INT NULL UNIQUE REFERENCES Users(UserID), DepartmentID INT NULL REFERENCES Departments(DepartmentID),
 EmployeeCode NVARCHAR(50) NOT NULL UNIQUE, JobTitle NVARCHAR(140), EmploymentType NVARCHAR(40) DEFAULT 'full_time',
 HireDate DATETIME2 NULL, Salary DECIMAL(18,2) DEFAULT 0, Status NVARCHAR(30) DEFAULT 'active',
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);
GO
IF OBJECT_ID('LeaveRequests','U') IS NULL
CREATE TABLE LeaveRequests(
 LeaveRequestID INT IDENTITY PRIMARY KEY, EmployeeID INT NOT NULL REFERENCES Employees(EmployeeID),
 LeaveType NVARCHAR(50) NOT NULL, StartDate DATETIME2 NOT NULL, EndDate DATETIME2 NOT NULL,
 Reason NVARCHAR(1000), Status NVARCHAR(30) DEFAULT 'pending', ApprovedBy INT NULL REFERENCES Users(UserID),
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);
GO
IF OBJECT_ID('Invoices','U') IS NULL
CREATE TABLE Invoices(
 InvoiceID INT IDENTITY PRIMARY KEY, OrganizationID INT NULL REFERENCES Organizations(OrganizationID),
 CustomerID INT NULL REFERENCES Customers(CustomerID), ClientUserID INT NULL REFERENCES Users(UserID),
 InvoiceNumber NVARCHAR(60) NOT NULL UNIQUE, Currency NVARCHAR(10) DEFAULT 'PKR',
 Subtotal DECIMAL(18,2) DEFAULT 0, TaxAmount DECIMAL(18,2) DEFAULT 0, TotalAmount DECIMAL(18,2) DEFAULT 0,
 PaidAmount DECIMAL(18,2) DEFAULT 0, Status NVARCHAR(30) DEFAULT 'draft', DueDate DATETIME2 NULL,
 Notes NVARCHAR(1000), CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);
GO
IF OBJECT_ID('Expenses','U') IS NULL
CREATE TABLE Expenses(
 ExpenseID INT IDENTITY PRIMARY KEY, OrganizationID INT NULL REFERENCES Organizations(OrganizationID),
 Category NVARCHAR(100) NOT NULL, Description NVARCHAR(500), Amount DECIMAL(18,2) NOT NULL,
 Currency NVARCHAR(10) DEFAULT 'PKR', ExpenseDate DATETIME2 NOT NULL, Status NVARCHAR(30) DEFAULT 'approved',
 CreatedBy INT NULL REFERENCES Users(UserID), CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);
GO
IF OBJECT_ID('SupportTickets','U') IS NULL
CREATE TABLE SupportTickets(
 TicketID INT IDENTITY PRIMARY KEY, OrganizationID INT NULL REFERENCES Organizations(OrganizationID),
 CreatedBy INT NOT NULL REFERENCES Users(UserID), AssignedTo INT NULL REFERENCES Users(UserID),
 Subject NVARCHAR(200) NOT NULL, Description NVARCHAR(MAX) NOT NULL, Priority NVARCHAR(30) DEFAULT 'medium',
 Status NVARCHAR(30) DEFAULT 'open', CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
 UpdatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);
GO
IF OBJECT_ID('KnowledgeDocuments','U') IS NULL
CREATE TABLE KnowledgeDocuments(
 KnowledgeDocumentID INT IDENTITY PRIMARY KEY, OrganizationID INT NULL REFERENCES Organizations(OrganizationID),
 Title NVARCHAR(255) NOT NULL, SourceType NVARCHAR(50) DEFAULT 'text', SourceURL NVARCHAR(1000),
 Content NVARCHAR(MAX) NOT NULL, IsActive BIT NOT NULL DEFAULT 1, CreatedBy INT NULL REFERENCES Users(UserID),
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);
GO
IF OBJECT_ID('KnowledgeChunks','U') IS NULL
CREATE TABLE KnowledgeChunks(
 KnowledgeChunkID INT IDENTITY PRIMARY KEY,
 KnowledgeDocumentID INT NOT NULL REFERENCES KnowledgeDocuments(KnowledgeDocumentID),
 OrganizationID INT NULL REFERENCES Organizations(OrganizationID), ChunkIndex INT NOT NULL,
 Content NVARCHAR(MAX) NOT NULL, TokenEstimate INT DEFAULT 0, CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);
GO
IF OBJECT_ID('AIConversations','U') IS NULL
CREATE TABLE AIConversations(
 ConversationID INT IDENTITY PRIMARY KEY, OrganizationID INT NULL REFERENCES Organizations(OrganizationID),
 UserID INT NOT NULL REFERENCES Users(UserID), Title NVARCHAR(255) DEFAULT 'New conversation',
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);
GO
IF OBJECT_ID('AIMessages','U') IS NULL
CREATE TABLE AIMessages(
 MessageID INT IDENTITY PRIMARY KEY, ConversationID INT NOT NULL REFERENCES AIConversations(ConversationID),
 Role NVARCHAR(20) NOT NULL, Content NVARCHAR(MAX) NOT NULL, SourcesJSON NVARCHAR(MAX),
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);
GO
CREATE INDEX IX_KnowledgeChunks_Document ON KnowledgeChunks(KnowledgeDocumentID);
GO
