"use client";
import {useEffect,useMemo,useState}from"react";
import{useRouter}from"next/navigation";
import api from"@/lib/api";
import{lmsApi}from"@/lib/lms";
import{Card,ErrorBox,btn,input,secondary}from"./Ui";

type User={UserID:number;FullName:string;Email:string;RoleID:number};
type Role={RoleID:number;RoleName:string};
const empty={Title:"",Slug:"",ShortDescription:"",Description:"",Thumbnail:"",Price:0,Level:"Beginner",Status:"draft",InstructorID:null as number|null,IsPublished:false};

export default function CourseEditor({courseId}:{courseId?:number}){
 const router=useRouter();const[f,setF]=useState(empty);const[error,setError]=useState("");const[saving,setSaving]=useState(false);const[users,setUsers]=useState<User[]>([]);const[roles,setRoles]=useState<Role[]>([]);
 useEffect(()=>{void Promise.all([api.get<User[]>("/users/"),api.get<Role[]>("/roles/")]).then(([u,r])=>{setUsers(u.data);setRoles(r.data)}).catch(()=>{});if(courseId)void lmsApi.course(courseId).then(x=>setF({...empty,...x,ShortDescription:x.ShortDescription||"",Description:x.Description||"",Thumbnail:x.Thumbnail||"",Price:Number(x.Price)})).catch(()=>setError("Course not found"))},[courseId]);
 const instructorRole=roles.find(r=>r.RoleName?.toUpperCase()==="INSTRUCTOR")?.RoleID;const instructors=useMemo(()=>users.filter(u=>instructorRole?u.RoleID===instructorRole:false),[users,instructorRole]);
 function changeTitle(v:string){setF(x=>({...x,Title:v,Slug:courseId?x.Slug:(x.Slug||v.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,""))}))}
 async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setError("");try{if(courseId)await lmsApi.updateCourse(courseId,f);else await lmsApi.createCourse(f);router.push("/dashboard/lms/courses")}catch(e:any){setError(e.response?.data?.detail||"Unable to save course")}finally{setSaving(false)}}
 return <Card className="max-w-4xl">{error&&<ErrorBox text={error}/>}<form onSubmit={submit} className="grid gap-4 md:grid-cols-2"><label className="font-semibold text-slate-800">Title<input className={input} value={f.Title} onChange={e=>changeTitle(e.target.value)} required/></label><label className="font-semibold text-slate-800">Slug<input className={input} value={f.Slug} onChange={e=>setF({...f,Slug:e.target.value})} required/></label><label className="md:col-span-2 font-semibold text-slate-800">Short description<input className={input} value={f.ShortDescription} onChange={e=>setF({...f,ShortDescription:e.target.value})}/></label><label className="md:col-span-2 font-semibold text-slate-800">Full description<textarea rows={6} className={input} value={f.Description} onChange={e=>setF({...f,Description:e.target.value})}/></label><label className="font-semibold text-slate-800">Thumbnail URL<input className={input} value={f.Thumbnail} onChange={e=>setF({...f,Thumbnail:e.target.value})} placeholder="https://..."/></label><label className="font-semibold text-slate-800">Price<input type="number" min="0" className={input} value={f.Price} onChange={e=>setF({...f,Price:Number(e.target.value)})}/></label><label className="font-semibold text-slate-800">Instructor<select className={input} value={f.InstructorID||""} onChange={e=>setF({...f,InstructorID:e.target.value?Number(e.target.value):null})}><option value="">Unassigned</option>{instructors.map(u=><option key={u.UserID} value={u.UserID}>{u.FullName} · {u.Email}</option>)}</select></label><label className="font-semibold text-slate-800">Level<select className={input} value={f.Level} onChange={e=>setF({...f,Level:e.target.value})}><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></label><label className="font-semibold text-slate-800">Status<select className={input} value={f.Status} onChange={e=>setF({...f,Status:e.target.value})}><option value="draft">Draft</option><option value="active">Active</option><option value="archived">Archived</option></select></label><label className="flex items-center gap-2 font-semibold text-slate-800"><input type="checkbox" checked={f.IsPublished} onChange={e=>setF({...f,IsPublished:e.target.checked})}/> Published for enrolled students</label><div className="md:col-span-2 flex gap-3"><button disabled={saving} className={btn}>{saving?"Saving...":"Save course"}</button><button type="button" className={secondary} onClick={()=>router.back()}>Cancel</button></div></form></Card>
}
